version: "3"
services:

  homeassistant:
    image: homeassistant/raspberrypi3-homeassistant:0.104.3
    container_name: homeassistant
    depends_on:
      - deconz
      - influxdb
      - grafana
      - telegraf
    healthcheck:
      test: ["CMD", "curl", "-s", "http://localhost:8123"]
      interval: 5s
      timeout: 3s
      retries: 100
    restart: unless-stopped
    privileged: true
    network_mode: host
    environment:
      - TZ=Europe/Amsterdam
    devices:
      - /dev/ttyAMA0
      - /dev/vcio
    volumes:
      - /mnt/usb-disk-2/homeassistant/data/config:/config
      - /root/.ssh/asus_router:/config/asus_router

  deconz:
    image: marthoc/deconz:armhf-2.05.72
    container_name: deconz
    restart: unless-stopped
    network_mode: host
    environment:
      - DECONZ_WEB_PORT=8080
      - DECONZ_WS_PORT=8443
      - TZ=Europe/Amsterdam
      - DECONZ_UPNP=0
      - DECONZ_DEVICE=/dev/ttyACM0 
    devices:
     - /dev/ttyACM0
    volumes:
      - /mnt/usb-disk-2/deconz/data/config:/root/.local/share/dresden-elektronik/deCONZ
      - /etc/localtime:/etc/localtime:ro

  influxdb:
    image: influxdb:1.7.9
    container_name: influxdb 
    restart: unless-stopped
    environment:
      - INFLUXDB_DB=home_assistant
      - INFLUXDB_USER=${INFLUXDB_USER}
      - INFLUXDB_USER_PASSWORD=${INFLUXDB_USER_PASSWORD}
    volumes:
      - /mnt/usb-disk-2/influxdb:/var/lib/influxdb
    ports:
      - 8086:8086

  grafana:
    image: grafana/grafana:6.6.0
    container_name: grafana
    depends_on:
      - telegraf
      - influxdb
    restart: unless-stopped
    user: "0"
    volumes:
      - /mnt/usb-disk-2/grafana:/var/lib/grafana
    ports:
      - 3000:3000

  telegraf:
    image: telegraf:1.13.2
    container_name: telegraf
    depends_on:
      - influxdb
    restart: unless-stopped
    links:
      - influxdb
    environment:
      - HOST_PROC=/host/proc
      - TELEGRAF_DB_PASSWORD=${TELEGRAF_DB_PASSWORD}
    volumes:
      - /proc:/host/proc:ro
      - /mnt/usb-disk-2:/hostfs:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./services/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro

        #  noip:
        #    build:
        #      context: ./services/noip
        #    container_name: noip
        #    restart: unless-stopped
        #    environment:
        #      - NOIP_USERNAME=${NOIP_EMAIL}
        #      - NOIP_PASSWORD=${NOIP_PASSWORD}
        #      - NOIP_HOSTNAME=${HOSTNAME}
        #      - PERIOD=60

  pihole:
    container_name: pihole
    image: pihole/pihole:4.3.2-1
    user: "0"
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
      - 80:80/tcp
      - 443:443/tcp
    environment:
      - TZ=Netherlands/Amsterdam
      - WEBPASSWORD=${PIHOLE_PASSWORD}
    volumes:
      - /mnt/usb-disk-2/etc-pihole/:/etc/pihole/
      - /mnt/usb-disk-2/etc-dnsmasq.d/:/etc/dnsmasq.d/
    dns:
      - 127.0.0.1
      - 1.1.1.1
    restart: unless-stopped

  transmission:
    image: linuxserver/transmission:2.94-r2-ls41
    container_name: transmission
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Amsterdam
      - TRANSMISSION_WEB_HOME=/combustion-release/
      - USER=${TRANSMISSION_USERNAME}
      - PASS=${TRANSMISSION_PASSWORD}
    volumes:
      - /mnt/usb-disk-2/transmission/data:/config
      - /mnt/usb-disk-2/transmission/downloads:/downloads
      - /mnt/usb-disk-2/transmission/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr:2.0.0.5337-ls95
    container_name: sonarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Amsterdam
    volumes:
      - /mnt/usb-disk-2/sonarr/data:/config
      - /mnt/usb-disk-2/sonarr/tvseries:/tv
      - /mnt/usb-disk-2/transmission/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped